app/models/cards.py
from app.models.db_instance import DBSingleton

db = DBSingleton.get_instance()


class Card(db.Model):
    __tablename__ = "cards"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    number = db.Column(db.String(80), nullable=False, unique=True)
    collection = db.Column(db.String(5), nullable=False)
    serial = db.Column(db.String(5), nullable=False)
    image = db.Column(db.String(200), nullable=False)
    rarity = db.Column(db.String(80), nullable=False)
    card_set = db.Column(db.String(80), nullable=False)
    cost = db.Column(db.Integer, nullable=False)
    card_type = db.Column(db.String(80), nullable=False)
    exburst = db.Column(db.String(5), nullable=False)
    limitbreak = db.Column(db.String(5), nullable=False, default="no")
    multiplayable = db.Column(db.String(5), nullable=False)
    power = db.Column(db.Integer, nullable=True)

    elements_list = db.relationship("Element", backref="cards", lazy=True)
    job_list = db.relationship("Job", backref="cards", lazy=True)
    categories_list = db.relationship("Category", backref="cards", lazy=True)
    abilities_list = db.relationship("Ability", backref="cards", lazy=True)


class Element(db.Model):
    __tablename__ = "elements"

    id = db.Column(db.Integer, primary_key=True)
    card_id = db.Column(db.Integer, db.ForeignKey(Card.id), nullable=False)
    order = db.Column(db.Integer, nullable=False)
    value = db.Column(db.String(80), nullable=False)

    card = db.relationship("Card", cascade="all,delete", backref="elements")


class Job(db.Model):
    __tablename__ = "jobs"

    id = db.Column(db.Integer, primary_key=True)
    card_id = db.Column(db.Integer, db.ForeignKey(Card.id), nullable=False)
    order = db.Column(db.Integer, nullable=False)
    value = db.Column(db.String(80), nullable=False)

    card = db.relationship("Card", cascade="all,delete", backref="jobs")


class Category(db.Model):
    __tablename__ = "categories"

    id = db.Column(db.Integer, primary_key=True)
    card_id = db.Column(db.Integer, db.ForeignKey(Card.id), nullable=False)
    order = db.Column(db.Integer, nullable=False)
    value = db.Column(db.String(80), nullable=False)

    card = db.relationship("Card", cascade="all,delete", backref="categories")


class Ability(db.Model):
    __tablename__ = "abilities"

    id = db.Column(db.Integer, primary_key=True)
    card_id = db.Column(db.Integer, db.ForeignKey(Card.id), nullable=False)
    row = db.Column(db.Integer, nullable=False)
    column = db.Column(db.Integer, nullable=False)
    value_type = db.Column(db.String(200), nullable=False)
    value = db.Column(db.Text, nullable=False)

    card = db.relationship("Card", cascade="all,delete", backref="abilities")

app/routes/cards.py
import json
import os
import urllib.parse

import pandas as pd
from flask import Blueprint, render_template, request
from sqlalchemy.orm import joinedload

from app.models.cards import Ability, Card, Category, Element, Job, db
from app.routes.constants import menu_items
from app.services.cards import get_card_detail, get_categories
from app.services.shared import get_pagination, parse_request_args

bp_cards = Blueprint("cards", __name__)

current_dir = os.path.dirname(os.path.abspath(__file__))
excel_path = os.path.join(current_dir, "..", "data", "scraping_result.xlsx")


@bp_cards.route("/<int:card_id>", methods=["GET"])
def card_detail(card_id):
    card = get_card_detail(card_id)
    return render_template("card_detail.html", card=card, menu=menu_items)


@bp_cards.route("/", methods=["GET"])
def show_cards():
    args, limit, page, order_by = parse_request_args(Card.collection, Card.serial)
    offset = limit * (page - 1)

    query = Card.query

    name = request.args.get("name")
    if name:
        query = query.filter(Card.name.ilike(f"%{name}%"))

    element = request.args.getlist("element")
    if element:
        query = query.join(Element).filter(Element.value.in_(element))

    card_type = request.args.getlist("card_type")
    if card_type:
        query = query.filter(Card.card_type.in_(card_type))

    cost = request.args.getlist("cost", type=int)
    if cost:
        query = query.filter(Card.cost.in_(cost))

    category_filter = request.args.get("category")
    if category_filter:
        query = query.join(Category).filter(Category.value == category_filter)

    operador = request.args.get("operator-power")
    power = request.args.get("power", type=int)
    if power:
        if operador == "=":
            query = query.filter(Card.power == power)
        elif operador == ">=":
            query = query.filter(Card.power >= power)
        elif operador == ">":
            query = query.filter(Card.power > power)
        elif operador == "<=":
            query = query.filter(Card.power <= power)
        elif operador == "<":
            query = query.filter(Card.power < power)

    rarity = request.args.get("rarity")
    if rarity:
        query = query.filter_by(rarity=rarity)

    job = request.args.get("job")
    if job:
        query = query.join(Job).filter(Job.value == job)

    ability_text = request.args.get("ability")
    if ability_text:
        query = query.join(Ability).filter(Ability.value.ilike(f"%{ability_text}%"))

    query = query.options(
        joinedload(Card.elements_list),
        joinedload(Card.job_list),
        joinedload(Card.categories_list),
        joinedload(Card.abilities_list),
    ).order_by(*order_by)

    pagination = get_pagination(query, page, limit)
    cards = query.limit(limit).offset(offset).all()
    args.setdefault("limit", request.args.get("limit", "24"))
    json_args = urllib.parse.urlencode(args)
    return render_template(
        "cards.html",
        cards=cards,
        args=json_args,
        menu=menu_items,
        title="Buscador",
        pagination=pagination,
        categories=get_categories(),
    )


@bp_cards.cli.command("populate")
def populate():
    df = pd.read_excel(excel_path)
    for _, row in df.iterrows():
        collection, serial = row["Number"].split("-") if pd.notna(row["Number"]) else (None, None)

        try:
            new_card = Card(
                name=row["Name"],
                number=row["Number"],
                image=row["Image"],
                rarity=row["Rarity"],
                card_set=row["Set"],
                cost=row["Cost"],
                card_type=row["Type"],
                exburst=row["Ex Burst"],
                multiplayable=row["Multiplayable"],
                power=row["Power"] if not pd.isna(row["Power"]) else None,
                collection=int(collection) if collection.isdigit() else collection,
                serial=serial,
            )

            db.session.add(new_card)
            db.session.commit()

            elements = json.loads(row["Element"])
            for order, element_value in enumerate(elements):
                element = Element(card_id=new_card.id, order=order + 1, value=element_value)
                db.session.add(element)

            jobs = json.loads(row["Job"])
            for order, job_value in enumerate(jobs):
                job = Job(card_id=new_card.id, order=order + 1, value=job_value)
                db.session.add(job)

            categories = json.loads(row["Categories"])
            for order, category_value in enumerate(categories):
                category = Category(card_id=new_card.id, order=order + 1, value=category_value)
                db.session.add(category)

            abilities = json.loads(row["Abilities"])
            for row_idx, ability_row in enumerate(abilities):
                for col_idx, ability in enumerate(ability_row):
                    for key, value in ability.items():
                        ability_entry = Ability(
                            card_id=new_card.id,
                            row=row_idx + 1,
                            column=col_idx + 1,
                            value_type=key,
                            value=value,
                        )
                        db.session.add(ability_entry)

                        if isinstance(value, str) and "limit break" in value.lower():
                            new_card.limit_break = "Yes"

            db.session.commit()

        except Exception:
            continue
    print("Datos cargados exitosamente.")

app/templates/card_detail.html
{% extends "menu.html" %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ card.name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
            text-align: left;
        }
        .card-container {
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 2px 2px 10px rgba(0, 0, 0, 0.1);
            max-width: 800px;
            margin: 20px auto;
        }

        .card-header {
            text-align: center;
            margin-bottom: 20px;
        }

        .card-content {
            display: flex;
            justify-content: flex-start;
            align-items: flex-start;
            width: 100%;
        }

        .card-image {
            flex: 1 1 40%;
            padding-right: 20px;
            text-align: center;
        }

        .card-image img {
            width: 100%;
            max-width: 250px;
            height: auto;
            border-radius: 5px;
        }

        .card-details {
            flex: 1 1 60%;
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
        }

        .card-details p {
            margin: 5px 0;
        }

        .abilities-container {
            display: flex;
            flex-wrap: wrap;
            gap: 10px;
            justify-content: center;
        }

        .ability-item {
            display: inline-flex;
            align-items: center;
        }

        .ability-image {
            width: 20px;
            height: 20px;
            margin-right: 5px;
        }

        img {
            width: 100%;
            max-width: 300px;
            border-radius: 5px;
        }
        h2 {
            margin: 10px 0;
        }
    </style>
</head>

<a href="{{ url_for('cards.show_cards') }}">⬅ Volver</a>

<body>
    <div class="card-container">
        <div class="card-header">
            <h2>{{ card.name }}</h2>
            <h3>{{ card.number }}</h3>
        </div>
        <div class="card-content">
            <div class="card-image">
                <img src="{{ card.image }}" alt="{{ card.name }}">
            </div>
            <div class="card-details">
                <p><strong>Rareza:</strong> {{ card.rarity }}</p>
                <p><strong>Set</strong> {{ card.card_set }}</p>
                <p><strong>Elementos:</strong> {{ card.elements_list | map(attribute="value") | join(", ") }}</p>
                <p><strong>Coste:</strong> {{ card.cost }}</p>
                <p><strong>Tipo:</strong> {{ card.card_type }}</p>
                <p><strong>EX Burst:</strong> {{ card.exburst }}</p>
                <p><strong>Multicopia:</strong> {{ card.multiplayable }}</p>
                <p><strong>Oficio:</strong> {{ card.job_list | map(attribute="value") | join(", ") }}</p>
                <p><strong>Categoría:</strong> {{ card.categories_list | map(attribute="value") | join(", ") }}</p>
                <p><strong>Poder:</strong> {{ card.power }}</p>
                <p><strong>Habilidad:</strong>
                    <div class="abilities-container">
                        {% for ability in card.abilities_list %}
                            <div class="ability-item">
                                {% if ability.value.startswith('http') %}
                                    <img src="{{ ability.value }}" alt="{{ ability.value }}" class="ability-image">
                                {% else %}
                                    <span>{{ ability.value }}</span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </p>
        </div>
    </div>
</body>
{% endblock %}

app/templates/cards.html
{% extends "menu.html" %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='card_finder.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='filter_card.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='pagination_card.css') }}">
</head>

<body>
    {% include "filters.html" %}

    <section>
        {% include "pagination.html" with context %}
    </section>

    <div class="grid-container">
        {% for card in cards %}
        <div class="card">
            <a href="{{ url_for('cards.card_detail', card_id=card.id) }}">
                <img src="{{ card.image }}" alt="Carta">
            </a>
            <label> {{ card.name }} </label>
            <label> {{ card.number }} </label>
        </div>
        {% endfor %}
    </div>
</body>
{% endblock %}

app/templates/filters.html
<div class="container">

    <!--<script>
        function filterByElement(element) {
            //console.log(element, "prueba")
            const url = new URL(window.location.href);
            url.searchParams.set('element', element);
            window.location.href = url.toString();
        }
    </script>-->

    <script>
        function toggleElementFilter(event, element) {
            event.preventDefault();  // Evita la navegación automática

            const url = new URL(window.location.href);
            let selectedElements = url.searchParams.getAll("element");

            if (selectedElements.includes(element)) {
                // Si ya está seleccionado, lo eliminamos
                selectedElements = selectedElements.filter(el => el !== element);
            } else {
                // Si no está seleccionado, lo agregamos
                selectedElements.push(element);
            }

            // Limpiar y volver a agregar los parámetros a la URL
            url.searchParams.delete("element");
            selectedElements.forEach(el => url.searchParams.append("element", el));

            window.location.href = url.toString();
        }
    </script>

    <script>
        function filterByType(card_type) {
            event.preventDefault();

            const url = new URL(window.location.href);
            let selectedCardTypes = url.searchParams.getAll("card_type");

            if (selectedCardTypes.includes(card_type)) {
                // Si ya está seleccionado, lo eliminamos
                selectedCardTypes = selectedCardTypes.filter(ct => ct !== card_type);
            } else {
                // Si no está seleccionado, lo agregamos
                selectedCardTypes.push(card_type);
            }

            // Limpiar y volver a agregar los parámetros a la URL
            url.searchParams.delete("card_type");
            selectedCardTypes.forEach(ct => url.searchParams.append("card_type", ct));

            // url.searchParams.set('card_type', card_type);
            window.location.href = url.toString();
        }
    </script>

    <script>
        function filterByCost(cost) {
            event.preventDefault();

            const url = new URL(window.location.href);
            let selectedCosts = url.searchParams.getAll("cost");

            if (selectedCosts.includes(cost)) {
                // Si ya está seleccionado, lo eliminamos
                selectedCosts = selectedCosts.filter(cs => cs !== cost);
            } else {
                // Si no está seleccionado, lo agregamos
                selectedCosts.push(cost);
            }

            // Limpiar y volver a agregar los parámetros a la URL
            url.searchParams.delete("cost");
            selectedCosts.forEach(cs => url.searchParams.append("cost", cs));

            // url.searchParams.set('cost', cost);
            window.location.href = url.toString();
        }
    </script>

    <form method="GET" action="{{ url_for('cards.show_cards') }}" class="filters">
        <input type="text" name="name" placeholder="Card Name">
    </form>
    <div class="filters-container">
        <div class="filter-group">
            <fieldset>
                <legend>Element</legend>
                {% for element in ["Fire", "Ice", "Wind", "Earth", "Lightning", "Water", "Light", "Dark"] %}
                    <!--<button class="filter-button" onclick="filterByElement('{{ element }}')">-->
                    {% set selected = "selected" if element in request.args.getlist('element') else "" %}
                    <button class="filter-button {{ selected }}" onclick="toggleElementFilter(event, '{{ element }}')">
                        <img src="https://ffdecks.com/assets/fftcg/markup/{{ element }}.png" alt="{{ element }}">
                    </button>
                {% endfor %}
            </fieldset>
        </div>
        <div class="filter-group">
            <fieldset>
                <legend>Type</legend>
                {% for card_type in ["Forward", "Backup", "Summon", "Monster"] %}
                    {% set selected = "selected" if card_type in request.args.getlist('card_type') else "" %}
                    <button class="filter-button {{ selected }}" onclick="filterByType('{{ card_type }}')" value="{{ card_type }}">{{ card_type }}</button>
                {% endfor %}
            </fieldset>
        </div>
        <div class="filter-group">
            <fieldset>
                <legend>Cost</legend>
                {% for cost in [1, 2, 3, 4, 5, 6 , 7, 8, 9, 10, 11] %}
                    {% set selected = "selected" if cost in request.args.getlist('cost') else "" %}
                    <button class="filter-button {{ selected }}" onclick="filterByCost('{{ cost }}')" value="{{ cost }}">{{ cost }}</button>
                {% endfor %}
            </fieldset>
        </div>
    </div>
    <form>
        <label for="category">Category:</label>
        <select name="category" id="category">
            <option value="">-- Todas --</option>
            {% for category in categories %}
                <option value="{{ category }}">{{ category }}</option>
            {% endfor %}
        </select>

        <div>
            <select name="operator-power">
                <option value="=">=</option>
                <option value=">=">>=</option>
                <option value=">">></option>
                <option value="<="><=</option>
                <option value="<"><</option>
            </select>
            <input type="number" name="power" placeholder="Power">
        </div>

        <label for="rarity">Rarity:</label>
        <select name="rarity">
            <option value="">-- Todas --</option>
            {% for rarity in ["Common", "Rare", "Hero", "Legend", "Starter", "Promo"] %}
                <option value="{{ rarity }}">{{ rarity }}</option>
            {% endfor %}
        </select>

        <input type="text" name="job" placeholder="Job">
        <input type="text" name="ability" placeholder="Ability Text">

        <button type="reset">Reset</button>
        <button type="submit">Buscar</button>
    </form>
</div>

app/templates/login.html
{% extends "menu.html" %}

{% block content %}
<form method="POST">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" required>
    <label for="password">Password</label>
    <input type="password" id="password" name="password" required>
    <button type="submit">Login</button>
</form>
{% endblock %}

app/templates/menu.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav>
        <ul>
            {% for item in menu %}
                <li>
                    <a href="{{ item.url }}" type="button">{{ item.name }}</a>
                    {% if item.submenu %}
                        <ul>
                            {% for subitem in item.submenu %}
                                <li><a href="{{ subitem.url }}" type="button">{{ subitem.name }}</a></li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </nav>

    <div>
        <h1>{{ title }}</h1>
    </div>
    <div>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}
    </div>
    {% block content %}{% endblock %}
</body>
</html>

app/templates/pagination.html
<div class="results-per-page">
    <!--<form method="GET" action="{{ url_for('cards.show_cards') }}?{{ args }}" class="limit-page">-->
    <form method="GET" class="limit-page">
        {% for key, value in request.args.items() %}
            {% if key not in ("limit", "page") %}
                <input type="hidden" name="{{ key }}" value="{{ value }}">
            {% endif %}
        {% endfor %}
        <label for="limit">Results Per Page</label>
        <select name="limit" id="limit" onchange="this.form.submit()">
            {% for value in [12, 24, 48, 96] %}
                <option value="{{ value }}" {% if request.args.get("limit", "24") == value|string %}selected{% endif %}>{{ value }}</option>
            {% endfor %}
        </select>
    </form>
    <!--
    <form class="pagination-container">
        <a href="{{ url_for('cards.show_cards') }}?{{ args|replace('page=' ~ request.args.get('page', ''), 'page=1') }}" class="{% if pagination['has_prev']!=1 %}disabled{% endif %}">⏮</a>
        <a href="{{ url_for('cards.show_cards') }}?{{ args|replace('page=' ~ request.args.get('page', '1'), 'page=' ~ (pagination['page'] - 1)) }}" class="{% if not pagination['has_prev'] %}disabled{% endif %}">◀</a>

        <span>{{ pagination["page"] }} de {{ pagination["pages"] }}</span>

        <a href="{{ url_for('cards.show_cards') }}?{{ args|replace('page=' ~ request.args.get('page', '1'), 'page=' ~ (pagination['page'] + 1)) }}" class="{% if not pagination['has_next'] %}disabled{% endif %}">▶</a>
        <a href="{{ url_for('cards.show_cards') }}?{{ args|replace('page=' ~ request.args.get('page', '1'), 'page=' ~ (pagination['pages'])) }}" class="{% if pagination['page']==pagination['pages'] %}disabled{% endif %}">⏭</a>
    </form>
    -->
    <form class="pagination-container">
        {% for key, value in request.args.items() %}
            {% if key != "page" %}
                <input type="hidden" name="{{ key }}" value="{{ value }}">
            {% endif %}
        {% endfor %}

        <button type="submit" name="page" value="1" {% if not pagination['has_prev'] %}disabled{% endif %}>⏮</button>
        <button type="submit" name="page" value="{{ pagination['page'] - 1 }}" {% if not pagination['has_prev'] %}disabled{% endif %}>◀</button>

        <span>{{ pagination["page"] }} de {{ pagination["pages"] }}</span>

        <button type="submit" name="page" value="{{ pagination['page'] + 1 }}" {% if not pagination['has_next'] %}disabled{% endif %}>▶</button>
        <button type="submit" name="page" value="{{ pagination['pages'] }}" {% if pagination['page'] == pagination['pages'] %}disabled{% endif %}>⏭</button>
    </form>
</div>

app/templates/register.html
{% extends "menu.html" %}

{% block content %}
<form method="POST">
    <label for="username">Username</label>
    <input type="text" id="username" name="username" required>
    <label for="email">Email</label>
    <input type="text" id="email" name="email" required>
    <label for="password">Password</label>
    <input type="password" id="password" name="password" required>
    <button type="submit">Register</button>
</form>
{% endblock %}